---
- name: Create Prometheus group
  group:
    name: prometheus
    system: yes

- name: Create Prometheus user
  user:
    name: prometheus
    system: yes
    group: prometheus

- name: Download Prometheus binary
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/0.17.0rc2/prometheus-0.17.0rc2.linux-amd64.tar.gz
    dest: /opt/prometheus.tar.gz
  register: prometheus_downloaded

- name: Unpack Prometheus
  unarchive:
    src: /opt/prometheus.tar.gz
    dest: /opt/
    creates: /opt/prometheus-0.17.0rc2.linux-amd64
    copy: no
    owner: prometheus
    group: prometheus

- name: Install Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus-0.17.0rc2.linux-amd64/prometheus.yml
  notify: Restart Prometheus

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  register: prometheus_service_installed

- name: Load new daemon definitions
  when: prometheus_service_installed.changed
  shell: systemctl daemon-reload
  register: daemon_reload

- name: Enable Prometheus service
  service: name=prometheus enabled=yes

- name: Start Prometheus
  service: name=prometheus state=started
