---
- name: Install dnsmasq
  apt: name=dnsmasq state=present

- name: Configure dnsmasq for Consul
  copy:
    content: "server=/consul/{{ ansible_eth1.ipv4.address }}#8600\n"
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
  notify: Restart dnsmasq

- name: Enable dnsmasq service
  service: name=dnsmasq enabled=yes

- name: Start dnsmasq service
  service: name=dnsmasq state=started

- name: Adding localhost as DNS server to running configuration
  lineinfile:
    line: "nameserver {{ ansible_eth1.ipv4.address }}"
    dest: /etc/resolv.conf
    insertbefore: BOF

- name: Add localhost as DNS server to dhclient
  lineinfile:
    line: "prepend domain-name-servers {{ ansible_eth1.ipv4.address }};"
    dest: /etc/dhcp/dhclient.conf
    insertbefore: EOF
