---
- name: Install dnsmasq
  apt: name=dnsmasq state=present
  register: dnsmasq_installed

- name: Configure dnsmasq for Consul
  copy:
    content: "server=/consul/127.0.0.1#8600\n"
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
  register: dnsmasq_configured

- name: Enable dnsmasq service
  when: dnsmasq_configured|success
  service: name=dnsmasq enabled=yes
  register: dnsmasq_enabled

- name: Restart dnsmasq
  when: dnsmasq_configured.changed and not dnsmasq_enabled.changed
  service: name=dnsmasq state=restarted

- name: Adding localhost as DNS server to running configuration
  when: dnsmasq_enabled|success
  lineinfile:
    line: "nameserver 127.0.0.1"
    dest: /etc/resolv.conf
    insertbefore: BOF

- name: Add localhost as DNS server to dhclient
  when: dnsmasq_enabled|success
  lineinfile:
    line: "prepend domain-name-servers 127.0.0.1;"
    dest: /etc/dhcp/dhclient.conf
    insertbefore: EOF
