---
- name: Install dnsmasq
  apt: name=dnsmasq state=present
  register: dnsmasq_installed

- name: Configure dnsmasq for Consul
  copy:
    content: "server=/consul/{{ ansible_eth1.ipv4.address }}#8600\n"
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
  register: dnsmasq_configured

- name: Enable dnsmasq service
  service: name=dnsmasq enabled=yes
  register: dnsmasq_enabled

- name: Restart dnsmasq
  when: dnsmasq_configured.changed and not dnsmasq_enabled.changed
  service: name=dnsmasq state=restarted

- name: Adding localhost as DNS server to running configuration
  when: dnsmasq_enabled|success
  lineinfile:
    line: "nameserver {{ ansible_eth1.ipv4.address }}"
    dest: /etc/resolv.conf
    insertbefore: BOF

- name: Add localhost as DNS server to dhclient
  lineinfile:
    line: "prepend domain-name-servers {{ ansible_eth1.ipv4.address }};"
    dest: /etc/dhcp/dhclient.conf
    insertbefore: EOF
