---
- name: Install OpenJDK
  apt: name=openjdk-7-jre-headless state=present

- name: Download Kafka
  get_url:
    url: http://www.eu.apache.org/dist/kafka/0.8.2.2/kafka_2.11-0.8.2.2.tgz
    dest: /opt/kafka.tgz

- name: Create Kafka group
  user:
    name: kafka
    system: yes

- name: Create Kafka user
  user:
    name: kafka
    system: yes
    group: kafka

- name: Unpack Kafka
  unarchive:
    src: /opt/kafka.tgz
    dest: /opt/
    creates: /opt/kafka_2.11-0.8.2.2
    copy: no
    owner: kafka
    group: kafka

- name: Create Kafka systemd service
  template:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
  register: kafka_service_installed

- name: Load new daemon definitions
  when: kafka_service_installed.changed
  shell: systemctl daemon-reload
  register: daemon_reload

- name: Install Kafka server.properties
  template:
    src: server.properties
    dest: /opt/kafka_2.11-0.8.2.2/config/server.properties
    owner: kafka
    group: kafka
  notify: Restart Kafka

- name: Enable Kafka service
  service: name=kafka enabled=yes

- name: Start Kafka
  service: name=kafka state=started
