---
- name: Create node-exporter group
  group:
    name: node_exporter
    system: yes

- name: Create node-exporter user
  user:
    name: node_exporter
    system: yes
    group: node_exporter

- name: Check if node-exporter has been installed
  stat: path=/opt/bin/node_exporter
  register: node_exporter_installed

- name: Download node-exporter binary
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/0.12.0rc3/node_exporter-0.12.0rc3.linux-amd64.tar.gz
    dest: /opt/node_exporter.tar.gz

- name: Unpack node-exporter
  when: node_exporter_installed.stat.islnk is not defined
  unarchive:
    src: /opt/node_exporter.tar.gz
    dest: /opt/bin
    creates: /opt/bin/node_exporter
    copy: no
    owner: node_exporter
    group: node_exporter

- name: Install node-exporter systemd service
  template:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service
  register: node_exporter_service_installed

- name: Load new daemon definitions
  when: node_exporter_service_installed.changed
  shell: systemctl daemon-reload
  register: daemon_reload

- name: Enable node-exporter service
  service: name=node-exporter enabled=yes

- name: Start node-exporter
  service: name=node-exporter state=started
