---
- name: Install the Elasticsearch signing key
  apt_key: keyserver=pgp.mit.edu id=D27D666CD88E42B4

- name: Add Elasticsearch repository
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/1.7/debian stable main"
    state=present

- name: Install Elasticsearch
  apt: name=elasticsearch state=present update_cache=yes

- name: Install fixed elasticsearch.service file
  template:
    src=elasticsearch.service
    dest=/usr/lib/systemd/system/elasticsearch.service
    owner=root
    group=root
  register: elasticsearch_service_installed

- name: Load new daemon definitions
  when: elasticsearch_service_installed.changed
  shell: systemctl daemon-reload

- name: Enable Elasticsearch service
  service: name=elasticsearch enabled=yes

- name: Install elasticsearch.conf
  template:
    src=elasticsearch.conf
    dest=/etc/default/elasticsearch
    owner=root
    group=root
  notify: Restart Elasticsearch

- name: Install elasticsearch.yml
  template:
    src=elasticsearch.yml
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
  notify: Restart Elasticsearch
