---
- name: Install the Elasticsearch signing key
  apt_key: keyserver=pgp.mit.edu id=D27D666CD88E42B4

- name: Add Elasticsearch repository
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/1.7/debian stable main"
    state=present

- name: Install Elasticsearch
  apt: name=elasticsearch state=present update_cache=yes

- name: Install fixed elasticsearch.service file
  template:
    src: elasticsearch.service.j2
    dest: /usr/lib/systemd/system/elasticsearch.service
  register: elasticsearch_service_installed

- name: Load new daemon definitions
  when: elasticsearch_service_installed.changed
  shell: systemctl daemon-reload

- name: Enable Elasticsearch service
  service: name=elasticsearch enabled=yes

- name: Install elasticsearch.conf
  template:
    src: elasticsearch.conf.j2
    dest: /etc/default/elasticsearch
  notify: Restart Elasticsearch

- name: Install elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart Elasticsearch
