---
- name: Install MongoDB
  apt: name=mongodb state=present

- name: Enable MongoDB
  service: name=mongodb enabled=yes

- name: Configure MongoDB
  template:
    src: mongodb.conf.j2
    dest: /etc/mongodb.conf
  notify: Restart MongoDB
