---
- name: Install MongoDB
  apt: name=mongodb state=present

- name: Enable MongoDB
  service: name=mongodb enabled=yes

- name: Configure MongoDB
  template:
    src=mongodb.conf
    dest=/etc/mongodb.conf
    owner=root
    group=root
  notify: Restart MongoDB
