---
- name: Install ZooKeeper
  apt: name=zookeeper state=present

- name: Create Zookeeper systemd service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  register: zookeeper_service_installed

- name: Set Zookeeper id
  copy:
    content: "{{ broker_id }}\n"
    dest: /var/lib/zookeeper/myid
  notify: Restart Zookeeper

- name: Load new daemon definitions
  when: zookeeper_service_installed.changed
  shell: systemctl daemon-reload
  register: daemon_reload

- name: Enable ZooKeeper
  service: name=zookeeper enabled=yes

- name: Start Zookeeper
  service: name=zookeeper state=started
