---
- name: Create Consul group
  group:
    name: consul
    system: yes

- name: Create Consul user
  user:
    name: consul
    system: yes
    group: consul

- name: Check if Consul has been installed
  stat: path=/opt/bin/consul
  register: consul_installed

- name: Download Consul binary
  when: consul_installed.stat.islnk is not defined
  get_url:
    url: https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip
    dest: /opt/consul.zip
  register: consul_downloaded

- name: Create /opt/bin
  file:
    path: /opt/bin
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Create /opt/etc/consul
  file:
    path: /opt/etc/consul
    owner: consul
    group: consul
    state: directory
    mode: 0755

- name: Install unzip
  apt: name=unzip state=present

- name: Unpack Consul
  when: consul_installed.stat.islnk is not defined
  unarchive:
    src: /opt/consul.zip
    dest: /opt/bin/
    creates: /opt/bin/consul
    copy: no
    owner: consul
    group: consul

- name: Create Consul config
  template:
    src: config.json
    dest: /opt/etc/consul/config.json
    owner: consul
    group: consul
  register: consul_configured

- name: Create Consul systemd service
  template:
    src: consul.service
    dest: /etc/systemd/system/consul.service
  register: consul_service_installed

- name: Load new daemon definitions
  when: consul_service_installed.changed
  shell: systemctl daemon-reload

- name: Create Consul data directory
  file:
    path: "{{ data_dir }}"
    owner: consul
    group: consul
    state: directory
    mode: 0755

- name: Enable Consul service
  service: name=consul enabled=yes

- name: Start Consul
  service: name=consul state=started
  register: consul_service_started

- name: Restart Consul
  when: (consul_configured.changed and not consul_service_started.changed)
  service: name=consul state=restarted
