---
- name: Create Consul group
  group:
    name: consul
    system: yes
  register: consul_group_created

- name: Create Consul user
  user:
    name: consul
    system: yes
    group: consul
  register: consul_user_created

- name: Check if Consul has been installed
  stat: path=/opt/bin/consul
  register: consul_installed

- name: Download Consul binary
  get_url:
    url: https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip
    dest: /tmp/consul.zip
  register: consul_downloaded

- name: Create /opt/bin
  file:
    path: /opt/bin
    owner: root
    group: root
    state: directory
    mode: 0755
  register: opt_bin_dir_created

- name: Create /opt/etc/consul
  file:
    path: /opt/etc/consul
    owner: consul
    group: consul
    state: directory
    mode: 0755
  register: opt_etc_consul_dir_created

- name: Install unzip
  apt: name=unzip state=present
  register: unzip_installed

- name: Unpack Consul
  when: (consul_downloaded|success and consul_installed.stat.islnk is not defined and opt_bin_dir_created|success and unzip_installed|success and consul_group_created|success and consul_user_created|success)
  unarchive:
    src: /tmp/consul.zip
    dest: /opt/bin/
    creates: /opt/bin/consul
    copy: no
    owner: consul
    group: consul
  register: consul_unpacked

- name: Check if Consul config exists
  stat: path=/opt/etc/consul/config.json
  register: consul_config_installed

- name: Create Consul config
  when: (consul_config_installed.stat.islnk is not defined and opt_etc_consul_dir_created|success)
  template:
    src: config.json
    dest: /opt/etc/consul/config.json
    owner: consul
    group: consul
  register: consul_configured

- name: Create Consul systemd service
  template:
    src: consul.service
    dest: /etc/systemd/system/consul.service
  register: consul_service_installed

- name: Load new daemon definitions
  when: consul_service_installed.changed
  shell: systemctl daemon-reload
  register: daemon_reload

- name: Create Consul data directory
  file:
    path: "{{ data_dir }}"
    owner: consul
    group: consul
    state: directory
    mode: 0755
  register: consul_data_dir_created

- name: Enable Consul service
  when: (daemon_reload.changed and consul_unpacked|success)
  service: name=consul enabled=yes
  register: consul_enabled

- name: Start Consul
  when: (consul_configured|success and daemon_reload|success)
  service: name=consul state=started
  register: consul_service_started

- name: Restart Consul
  when: (consul_configured.changed and not consul_service_started.changed)
  service: name=consul state=restarted
